### ISSUE TITLE
DanteCache Missing?

### ISSUE THREAD

**Issue by marcnnn** [chris-ritsen/network-audio-controller#13] opened 2023-03-14 22:14 UTC
Hey,
I would like to help to develop.

But it looks like some code is missing on master?

Traceback (most recent call last):
  File "/home/marc/Projects/network-audio-controller/netaudio/__main__.py", line 12, in <module>
    from netaudio.console.application import main
  File "/home/marc/Projects/network-audio-controller/netaudio/__init__.py", line 10, in <module>
    from .console.application import main
  File "/home/marc/Projects/network-audio-controller/netaudio/console/__init__.py", line 1, in <module>
    from .commands.channel import ChannelCommand
  File "/home/marc/Projects/network-audio-controller/netaudio/console/commands/__init__.py", line 5, in <module>
    from .subscription import SubscriptionCommand
  File "/home/marc/Projects/network-audio-controller/netaudio/console/commands/subscription/__init__.py", line 5, in <module>
    from ._list import SubscriptionListCommand
  File "/home/marc/Projects/network-audio-controller/netaudio/console/commands/subscription/_list.py", line 13, in <module>
    from netaudio.dante.cache import DanteCache
ModuleNotFoundError: No module named 'netaudio.dante.cache'

**Comment by bfranske** [comment] 2023-03-14 22:30
Duplicate of Issue #12 . I think the DanteCache feature was never fully implemented/working when committed. Check an older version like https://github.com/chris-ritsen/network-audio-controller/tree/81eae884464211cdfb0e9d9093cea0146a3cc4f7

**Comment by weltenseglr** [comment] 2023-03-19 12:14
Might be a duplicate.
In commit [a9cece2](https://github.com/chris-ritsen/network-audio-controller/tree/a9cece2fc351a302aa210ad1367a9708dea5139f) the server + cache were initially pushed. However, in the following commit [dcb54c1](https://github.com/chris-ritsen/network-audio-controller/commit/dcb54c1473c8bdd9a3fd875b0cf3ae570fa1c2da) imports missing code
`from netaudio.dante.cache import DanteCache`.

I'd guess the server + cache all in one have been refactored into two sperate modules server and cache, but @chris-ritsen missed to add all files to his commit?

@bfranske is [a9cece2](https://github.com/chris-ritsen/network-audio-controller/tree/a9cece2fc351a302aa210ad1367a9708dea5139f) working for you?

**Closed** 2024-08-30 10:42 UTC
